knpu_oauth2_client:
    clients:
        google:
            # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}