# config/services.yaml
parameters:
    # Ajoutez vos paramètres globaux ici avec le préfixe % pour l'utilisation dans les services
    # Exemple : 'locale': 'en'
    env(TWITCH_CLIENT_ID): '%env(string:TWITCH_CLIENT_ID)%'
    env(TWITCH_CLIENT_SECRET): '%env(string:TWITCH_CLIENT_SECRET)%'
    images_directory: '%kernel.project_dir%/public/assets/uploads/'
    admin_secret: '%env(ADMIN_SECRET)%'

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $clientId: '%env(TWITCH_CLIENT_ID)%'
            $clientSecret: '%env(TWITCH_CLIENT_SECRET)%'
            $admin_secret: '%env(ADMIN_SECRET)%'

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configure services
    App\Service\TwitchAuthService:
        arguments:
            $clientId: '%env(TWITCH_CLIENT_ID)%'
            $clientSecret: '%env(TWITCH_CLIENT_SECRET)%'
            $logger: '@logger'

    App\Service\InsultFilter:
        arguments:
            $insultList: ['stupid', 'idiot', 'dumb']

    App\Security\Redirect403:
        arguments: ['@router']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    App\Security\Redirect404:
        arguments: ['@router']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    App\Security\Redirect500:
        arguments: ['@router']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    # Example of a service definition:
    # App\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'